/**
 * @fileoverview CSS-in-JS Style Manager for Dialogs
 *
 * Manages CSS injection for dialog components. Uses a singleton pattern
 * to inject styles only once and provides theming support.
 *
 * Features:
 * - One-time style injection
 * - Scoped CSS classes with lwc-pro prefix
 * - Consistent TradingView-inspired styling
 * - Support for light/dark themes (future)
 *
 * @example
 * ```typescript
 * // Inject styles before creating any dialogs
 * StyleManager.inject();
 *
 * // Optionally inject with custom theme
 * StyleManager.inject('dark');
 * ```
 */

/**
 * Theme configuration
 */
export interface DialogTheme {
  // Background colors
  overlayBg: string;
  dialogBg: string;
  footerBg: string;

  // Text colors
  textPrimary: string;
  textSecondary: string;
  textMuted: string;

  // Border colors
  borderColor: string;
  borderLight: string;

  // Primary action color
  primaryColor: string;
  primaryHover: string;

  // Shadows
  dialogShadow: string;
}

/**
 * Light theme (default)
 */
const LIGHT_THEME: DialogTheme = {
  overlayBg: 'rgba(0, 0, 0, 0.5)',
  dialogBg: '#ffffff',
  footerBg: '#f8f9fa',
  textPrimary: '#131722',
  textSecondary: '#787b86',
  textMuted: '#b2b5be',
  borderColor: '#e0e3e7',
  borderLight: 'rgba(0, 0, 0, 0.1)',
  primaryColor: '#2962ff',
  primaryHover: '#1e53e5',
  dialogShadow: '0 8px 32px rgba(0, 0, 0, 0.25)',
};

/**
 * Dark theme
 */
const DARK_THEME: DialogTheme = {
  overlayBg: 'rgba(0, 0, 0, 0.7)',
  dialogBg: '#1e222d',
  footerBg: '#171b26',
  textPrimary: '#d1d4dc',
  textSecondary: '#787b86',
  textMuted: '#4c525e',
  borderColor: '#363a45',
  borderLight: 'rgba(255, 255, 255, 0.1)',
  primaryColor: '#2962ff',
  primaryHover: '#1e53e5',
  dialogShadow: '0 8px 32px rgba(0, 0, 0, 0.5)',
};

/**
 * CSS class prefix for namespacing
 */
const CSS_PREFIX = 'lwc-pro';

/**
 * Style ID for the injected style element
 */
const STYLE_ID = `${CSS_PREFIX}-dialog-styles`;

/**
 * Generate CSS styles for the given theme
 */
function generateStyles(theme: DialogTheme): string {
  return `
/* ============================================================================
   Lightweight Charts Pro - Dialog Styles
   Generated by StyleManager - DO NOT EDIT DIRECTLY
   ============================================================================ */

/* Reset & Base */
.${CSS_PREFIX}-dialog-overlay,
.${CSS_PREFIX}-dialog-overlay * {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

/* Overlay */
.${CSS_PREFIX}-dialog-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: ${theme.overlayBg};
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10000;
  padding: 8px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}

/* Dialog Container */
.${CSS_PREFIX}-dialog {
  background-color: ${theme.dialogBg};
  border-radius: 8px;
  box-shadow: ${theme.dialogShadow};
  overflow: hidden;
  outline: none;
}

.${CSS_PREFIX}-dialog-sm {
  width: 240px;
}

.${CSS_PREFIX}-dialog-md {
  width: 320px;
}

.${CSS_PREFIX}-dialog-lg {
  width: 480px;
}

/* Dialog Header */
.${CSS_PREFIX}-dialog-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 6px 6px 6px;
  border-bottom: 1px solid ${theme.borderColor};
}

.${CSS_PREFIX}-dialog-title {
  font-size: 14px;
  font-weight: 500;
  color: ${theme.textPrimary};
  line-height: 20px;
}

.${CSS_PREFIX}-dialog-close {
  background: none;
  border: none;
  color: ${theme.textPrimary};
  font-size: 24px;
  line-height: 1;
  cursor: pointer;
  padding: 0;
  width: 24px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  opacity: 0.6;
  transition: opacity 0.2s;
}

.${CSS_PREFIX}-dialog-close:hover {
  opacity: 1;
}

/* Dialog Content */
.${CSS_PREFIX}-dialog-content {
  padding: 6px;
}

/* Dialog Footer */
.${CSS_PREFIX}-dialog-footer {
  display: flex;
  justify-content: flex-end;
  gap: 6px;
  padding: 8px 6px;
  border-top: 1px solid ${theme.borderColor};
  background-color: ${theme.footerBg};
}

/* Buttons */
.${CSS_PREFIX}-btn {
  padding: 6px 12px;
  border-radius: 4px;
  font-size: 13px;
  font-weight: 400;
  cursor: pointer;
  font-family: inherit;
  transition: background-color 0.15s ease;
}

.${CSS_PREFIX}-btn-secondary {
  border: 1px solid ${theme.borderColor};
  background-color: ${theme.dialogBg};
  color: ${theme.textPrimary};
}

.${CSS_PREFIX}-btn-secondary:hover {
  background-color: ${theme.footerBg};
}

.${CSS_PREFIX}-btn-primary {
  border: 1px solid ${theme.primaryColor};
  background-color: ${theme.primaryColor};
  color: #ffffff;
  font-weight: 500;
}

.${CSS_PREFIX}-btn-primary:hover {
  background-color: ${theme.primaryHover};
}

/* Color Palette */
.${CSS_PREFIX}-color-grid {
  display: grid;
  grid-template-columns: repeat(10, 15px);
  gap: 1px;
  margin-bottom: 6px;
  justify-content: center;
}

.${CSS_PREFIX}-color-btn {
  width: 15px;
  height: 15px;
  border: 1px solid ${theme.borderLight};
  border-radius: 2px;
  cursor: pointer;
  padding: 0;
  transition: all 0.15s ease;
}

.${CSS_PREFIX}-color-btn:hover {
  transform: scale(1.15);
  z-index: 1;
}

.${CSS_PREFIX}-color-btn.selected {
  border: 2px solid ${theme.primaryColor};
}

/* Custom Color Picker */
.${CSS_PREFIX}-custom-picker-btn {
  width: 100%;
  height: 24px;
  border: 1px dashed ${theme.borderColor};
  border-radius: 4px;
  background-color: transparent;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  color: ${theme.textSecondary};
  font-size: 12px;
  margin: 0 auto 6px auto;
  font-family: inherit;
}

.${CSS_PREFIX}-custom-picker-btn:hover {
  border-color: ${theme.textSecondary};
}

.${CSS_PREFIX}-custom-picker-panel {
  margin-bottom: 6px;
  border: 1px solid ${theme.borderColor};
  border-radius: 8px;
  padding: 8px;
  background-color: ${theme.dialogBg};
}

.${CSS_PREFIX}-color-area {
  width: 100%;
  height: 120px;
  border-radius: 4px;
  cursor: crosshair;
  margin-bottom: 8px;
  position: relative;
}

.${CSS_PREFIX}-color-area-indicator {
  position: absolute;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  border: 2px solid #ffffff;
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.3);
  transform: translate(-50%, -50%);
  pointer-events: none;
}

.${CSS_PREFIX}-hue-slider {
  width: 100%;
  height: 8px;
  background: linear-gradient(to right,
    #ff0000 0%,
    #ffff00 17%,
    #00ff00 33%,
    #00ffff 50%,
    #0000ff 67%,
    #ff00ff 83%,
    #ff0000 100%);
  border-radius: 4px;
  appearance: none;
  -webkit-appearance: none;
  cursor: pointer;
}

.${CSS_PREFIX}-hue-slider::-webkit-slider-thumb {
  appearance: none;
  -webkit-appearance: none;
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.2);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
  cursor: pointer;
}

.${CSS_PREFIX}-hue-slider::-moz-range-thumb {
  width: 12px;
  height: 12px;
  border-radius: 50%;
  background: #ffffff;
  border: 1px solid rgba(0, 0, 0, 0.2);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
  cursor: pointer;
}

/* Opacity Slider */
.${CSS_PREFIX}-opacity-section {
  padding: 0 6px 6px 6px;
  border-bottom: 1px solid ${theme.borderColor};
}

.${CSS_PREFIX}-opacity-label {
  display: block;
  font-size: 12px;
  font-weight: 400;
  color: ${theme.textSecondary};
  margin-bottom: 4px;
}

.${CSS_PREFIX}-opacity-row {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 0 2px;
}

.${CSS_PREFIX}-opacity-slider-container {
  position: relative;
  flex: 1;
  height: 20px;
  border-radius: 4px;
  overflow: hidden;
  border: 1px solid ${theme.borderColor};
}

.${CSS_PREFIX}-opacity-slider {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  appearance: none;
  -webkit-appearance: none;
  background: transparent;
  cursor: pointer;
}

.${CSS_PREFIX}-opacity-slider::-webkit-slider-thumb {
  appearance: none;
  -webkit-appearance: none;
  width: 4px;
  height: 20px;
  background: ${theme.textPrimary};
  cursor: pointer;
}

.${CSS_PREFIX}-opacity-slider::-moz-range-thumb {
  width: 4px;
  height: 20px;
  background: ${theme.textPrimary};
  cursor: pointer;
  border: none;
}

.${CSS_PREFIX}-opacity-value {
  font-size: 12px;
  color: ${theme.textPrimary};
  font-weight: 400;
  width: 40px;
  text-align: right;
  border: none;
  background: transparent;
  outline: none;
  font-family: inherit;
}

/* Line Editor */
.${CSS_PREFIX}-line-preview {
  width: 100%;
  height: 20px;
  border-radius: 4px;
  border: 1px solid ${theme.borderColor};
  margin-bottom: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.${CSS_PREFIX}-section {
  margin-bottom: 12px;
}

.${CSS_PREFIX}-section:last-child {
  margin-bottom: 0;
}

.${CSS_PREFIX}-section-label {
  font-size: 12px;
  font-weight: 400;
  color: ${theme.textSecondary};
  margin-bottom: 6px;
  display: block;
}

/* Thickness Options */
.${CSS_PREFIX}-thickness-options {
  display: flex;
  gap: 8px;
  justify-content: flex-start;
}

.${CSS_PREFIX}-thickness-btn {
  width: 32px;
  height: 32px;
  border: 1px solid ${theme.borderColor};
  border-radius: 4px;
  background-color: ${theme.dialogBg};
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.15s ease;
}

.${CSS_PREFIX}-thickness-btn:hover {
  border-color: ${theme.textSecondary};
}

.${CSS_PREFIX}-thickness-btn.selected {
  border-color: ${theme.primaryColor};
  background-color: rgba(41, 98, 255, 0.1);
}

/* Line Style Options */
.${CSS_PREFIX}-line-style-options {
  display: flex;
  gap: 8px;
}

.${CSS_PREFIX}-line-style-btn {
  flex: 1;
  height: 32px;
  border: 1px solid ${theme.borderColor};
  border-radius: 4px;
  background-color: ${theme.dialogBg};
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.15s ease;
  overflow: hidden;
}

.${CSS_PREFIX}-line-style-btn:hover {
  border-color: ${theme.textSecondary};
}

.${CSS_PREFIX}-line-style-btn.selected {
  border-color: ${theme.primaryColor};
  background-color: rgba(41, 98, 255, 0.1);
}

/* Tabs */
.${CSS_PREFIX}-tabs-container {
  display: flex;
  align-items: center;
  border-bottom: 1px solid ${theme.borderColor};
  position: relative;
}

.${CSS_PREFIX}-tabs-scroll-btn {
  width: 24px;
  height: 32px;
  border: none;
  background: transparent;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  color: ${theme.textSecondary};
  flex-shrink: 0;
}

.${CSS_PREFIX}-tabs-scroll-btn:hover {
  color: ${theme.textPrimary};
}

.${CSS_PREFIX}-tabs-scroll-btn:disabled {
  opacity: 0.3;
  cursor: default;
}

.${CSS_PREFIX}-tabs-list {
  display: flex;
  overflow-x: hidden;
  flex: 1;
  scroll-behavior: smooth;
}

.${CSS_PREFIX}-tab {
  padding: 8px 12px;
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 13px;
  color: ${theme.textSecondary};
  white-space: nowrap;
  position: relative;
  font-family: inherit;
}

.${CSS_PREFIX}-tab:hover {
  color: ${theme.textPrimary};
}

.${CSS_PREFIX}-tab.active {
  color: ${theme.primaryColor};
  font-weight: 500;
}

.${CSS_PREFIX}-tab.active::after {
  content: '';
  position: absolute;
  bottom: -1px;
  left: 0;
  right: 0;
  height: 2px;
  background-color: ${theme.primaryColor};
}

/* Form Controls */
.${CSS_PREFIX}-form-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 0;
  border-bottom: 1px solid ${theme.borderColor};
}

.${CSS_PREFIX}-form-row:last-child {
  border-bottom: none;
}

.${CSS_PREFIX}-form-label {
  font-size: 13px;
  color: ${theme.textPrimary};
}

.${CSS_PREFIX}-checkbox {
  width: 18px;
  height: 18px;
  cursor: pointer;
  accent-color: ${theme.primaryColor};
}

.${CSS_PREFIX}-input {
  padding: 6px 8px;
  border: 1px solid ${theme.borderColor};
  border-radius: 4px;
  font-size: 13px;
  color: ${theme.textPrimary};
  background-color: ${theme.dialogBg};
  font-family: inherit;
  width: 80px;
}

.${CSS_PREFIX}-input:focus {
  outline: none;
  border-color: ${theme.primaryColor};
}

.${CSS_PREFIX}-select {
  padding: 6px 8px;
  border: 1px solid ${theme.borderColor};
  border-radius: 4px;
  font-size: 13px;
  color: ${theme.textPrimary};
  background-color: ${theme.dialogBg};
  font-family: inherit;
  cursor: pointer;
}

/* Line Editor Button */
.${CSS_PREFIX}-line-editor-btn {
  height: 24px;
  min-width: 60px;
  border: 1px solid ${theme.borderColor};
  border-radius: 4px;
  background-color: ${theme.dialogBg};
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 4px;
  padding: 0 8px;
  font-size: 12px;
  color: ${theme.textPrimary};
  font-family: inherit;
}

.${CSS_PREFIX}-line-editor-btn:hover {
  border-color: ${theme.textSecondary};
}

.${CSS_PREFIX}-line-preview-small {
  width: 24px;
  height: 2px;
}

/* Color Picker Button */
.${CSS_PREFIX}-color-picker-btn {
  width: 24px;
  height: 24px;
  border: 1px solid ${theme.borderColor};
  border-radius: 4px;
  cursor: pointer;
  position: relative;
}

.${CSS_PREFIX}-color-picker-btn:hover {
  border-color: ${theme.textSecondary};
}

/* Color preview with transparency indicator */
.${CSS_PREFIX}-color-picker-btn::before {
  content: '';
  position: absolute;
  top: 2px;
  left: 2px;
  right: 2px;
  bottom: 2px;
  background: repeating-conic-gradient(#ccc 0% 25%, transparent 0% 50%) 50% / 8px 8px;
  border-radius: 2px;
}

.${CSS_PREFIX}-color-picker-btn .color-fill {
  position: absolute;
  top: 2px;
  left: 2px;
  right: 2px;
  bottom: 2px;
  border-radius: 2px;
}

/* Scrollbar styles */
.${CSS_PREFIX}-dialog ::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}

.${CSS_PREFIX}-dialog ::-webkit-scrollbar-track {
  background: transparent;
}

.${CSS_PREFIX}-dialog ::-webkit-scrollbar-thumb {
  background: ${theme.borderColor};
  border-radius: 3px;
}

.${CSS_PREFIX}-dialog ::-webkit-scrollbar-thumb:hover {
  background: ${theme.textSecondary};
}

/* Animation */
@keyframes ${CSS_PREFIX}-fade-in {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes ${CSS_PREFIX}-scale-in {
  from {
    opacity: 0;
    transform: scale(0.95);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

.${CSS_PREFIX}-dialog-overlay {
  animation: ${CSS_PREFIX}-fade-in 0.15s ease-out;
}

.${CSS_PREFIX}-dialog {
  animation: ${CSS_PREFIX}-scale-in 0.15s ease-out;
}
`;
}

/**
 * Style Manager for dialog CSS injection
 *
 * Singleton pattern ensures styles are only injected once.
 */
export class StyleManager {
  private static _injected: boolean = false;
  private static _styleElement: HTMLStyleElement | null = null;
  private static _currentTheme: 'light' | 'dark' = 'light';

  /**
   * Inject styles into the document head
   *
   * Safe to call multiple times - will only inject once.
   *
   * @param theme - The theme to use ('light' or 'dark')
   */
  public static inject(theme: 'light' | 'dark' = 'light'): void {
    if (typeof document === 'undefined') {
      return; // SSR safety
    }

    // If already injected with same theme, skip
    if (this._injected && this._currentTheme === theme) {
      return;
    }

    // Remove existing styles if theme changed
    if (this._styleElement) {
      this._styleElement.remove();
      this._styleElement = null;
    }

    const themeConfig = theme === 'dark' ? DARK_THEME : LIGHT_THEME;
    const css = generateStyles(themeConfig);

    const style = document.createElement('style');
    style.id = STYLE_ID;
    style.textContent = css;
    document.head.appendChild(style);

    this._styleElement = style;
    this._injected = true;
    this._currentTheme = theme;
  }

  /**
   * Remove injected styles
   *
   * Useful for cleanup or theme switching.
   */
  public static remove(): void {
    if (this._styleElement) {
      this._styleElement.remove();
      this._styleElement = null;
      this._injected = false;
    }
  }

  /**
   * Check if styles are currently injected
   */
  public static get isInjected(): boolean {
    return this._injected;
  }

  /**
   * Get the current theme
   */
  public static get currentTheme(): 'light' | 'dark' {
    return this._currentTheme;
  }

  /**
   * Get the CSS class prefix
   */
  public static get prefix(): string {
    return CSS_PREFIX;
  }

  /**
   * Get a prefixed class name
   *
   * @param className - The base class name
   * @returns The prefixed class name
   */
  public static cls(className: string): string {
    return `${CSS_PREFIX}-${className}`;
  }

  /**
   * Get theme configuration
   */
  public static getTheme(theme: 'light' | 'dark' = 'light'): DialogTheme {
    return theme === 'dark' ? { ...DARK_THEME } : { ...LIGHT_THEME };
  }
}

// Export themes for external use
export { LIGHT_THEME, DARK_THEME, CSS_PREFIX };
