name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run linting
      run: |
        ruff check .
        ruff format --check .

    - name: Run tests
      run: |
        pytest tests/ -v

    - name: Build documentation
      run: |
        pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python
        mkdocs build

    - name: Check documentation
      run: |
        # Verify docs built successfully
        test -f docs/index.html
        echo "Documentation built successfully!"
